---
title: "p8105_hw5_bjl2150"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(ggridges)
```

# Problem 1
```{r}
# Made a dataframe with all the file names
long = tibble(longitudinal = list.files(path = "./data", full.names = TRUE),
map(longitudinal, read_csv)) %>%
  unnest()


long_tidy = separate(long, longitudinal, into = c("control_arm", "id.csv"), sep = "_") %>%
  separate(control_arm, into = c("data", "period", "control_arm"), sep = "/") %>%
  select(-data, -period)




# Tidying the dataframe so that variable 'week' is in one column rather than spread out.
long_gather = gather(long_tidy, key = week, value = n, week_1:week_8) %>%
  separate(week, into = c("number", "week"), sep = "_") %>%
  select(-number)

# Making of spaghetti plot

long_spaghetti = long_gather %>%
  group_by(id.csv)
  

ggplot(long_spaghetti, aes(x = week, y = n, color = control_arm)) +
  geom_line()
```
# %>% separate(id.csv, into = c("id", "csv"), sep = ".")


brfss_spaghetti = brfss %>%
  group_by(locationabbr, year) %>%
  distinct(locationdesc) %>%
  summarize(location_numbers = n()) %>%
  ggplot(aes(x = year, y = location_numbers, color = locationabbr)) + 
  geom_line() 


# Problem 2

```{r}
library(tidyverse)
library(rvest)
library(httr)

homicide_data = read_csv(file = "./homicidedata.csv")
```
### Description of raw data:

The homicide_data shows the numbers of homicides within the 

```{r}
# Making of the new variable 'city_state'
homicide_citystate = homicide_data %>%
  mutate(city_state = str_c(city, ", " , state)) %>%
  select(victim_race, victim_age, disposition, city_state)

homicide_summarize = homicide_citystate %>% 
  filter(disposition %in% c("Closed without arrest", "Open/No arrest")) 



```



